### ISSUE TITLE
TypeError: Cannot read property 'session' of undefined

### ISSUE THREAD

**Issue by AIBluefisher** [luin/ranaly#9]
TypeError: Cannot read property 'session' of undefined
    at Object.<anonymous> (/home/chenyu/Documents/ranaly/ranaly.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by 390467556** [comment]
I hava an same question. How to solve it?

**Comment by leoshus** [comment]
replace it with express-session :
`require('express-session').MemoryStore();`
